### ISSUE TITLE
quastion about the FIQA process

### ISSUE THREAD

**Issue by abcsimple** [fdbtrs/CR-FIQA#3]
hi, thx for your amazing job! I have a question about the FIQA part. I’m confused about the “pair” meaning in XQLFW, also, why should I save image in a BGR way (by running extract_xqlfw.py) before get the quality score?

If i have some images in a folder, can I compute the score of these images directly without saving in BGR format?

**Comment by abcsimple** [comment]
plus, when compute

**Comment by abcsimple** [comment]
plus, when compute the quality scores by the current code, some images are computed more than one time, because some images appeared more than once in ‘image_path_list.txt’, which doesn’t make sense as a path file for quality assessment

**Comment by fdbtrs** [comment]
Opencv read  function reads image as BGR. The provided code is correct. You can optionally save the image as RGB, AND make sure to convert the channel order after leading it
