### ISSUE TITLE
BGR vs RGB

### ISSUE THREAD

**Issue by 3dimaging** [fdbtrs/CR-FIQA#9]
Great work!
I would like to know if there is any specific reason you use BGR format instead of regular RGB for the model training and testing.

Thank you!

**Comment by fdbtrs** [comment]
model training and testing are based on RGB. be aware that open cv read function by default changes RGB to BGR (cv2.imread)

**Comment by blueclowd** [comment]
Just wanna check that if the expected input format is RGB instead of BGR, should we modify the below script in FaceModel.py from
```
if (color =="RGB"):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
```
to 
```
if (color =="BGR"):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
```

Thanks
